language: node_js
cache: npm
jobs:
  include:
    - stage: test
      script: npm run tsc
    - stage: deploy
      before_script: npm i -g now
      script: npm run deploy:production
stages:
  - test
  - name: deploy
    if: branch = master